on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-macos:
    runs-on: macos-latest
    steps:
      - name: Install homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: Install LLVM
        run: brew install llvm
      - name: Install pcre
        run: brew install pcre
      - name: Checkout project
        uses: actions/checkout@v3.0.0
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Setup nightly Zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - name: Run tests
        run: LLVM_PATH=/usr/local/opt/llvm BUZZ_PATH=./dist zig build test -Duse_mimalloc=false
      - name: Run tests JIT on
        run: LLVM_PATH=/usr/local/opt/llvm BUZZ_PATH=./dist zig build test -Duse_mimalloc=false -Djit
      - name: Run tests JIT debug
        run: LLVM_PATH=/usr/local/opt/llvm BUZZ_PATH=./dist zig build test -Duse_mimalloc=false -Djit -Djit_debug
  # FIXME: doesn't find LLVM
  # test-linux:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Install LLVM
  #       run: sudo apt-get update && sudo DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends llvm llvm-dev libllvm15
  #     - name: Checkout project
  #       uses: actions/checkout@v3.0.0
  #     - name: Checkout submodules
  #       run: git submodule update --init --recursive
  #     - name: Setup nightly Zig
  #       uses: goto-bus-stop/setup-zig@v1
  #       with:
  #         version: master
  #     - name: Build
  #       run: LLVM_PATH=/usr/lib/x86_64-linux-gnu zig build -Duse_mimalloc=false
  #     - name: Run tests
  #       run: LLVM_PATH=/usr/lib/x86_64-linux-gnu BUZZ_PATH=./dist zig build test -Duse_mimalloc=false
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - name: Setup nightly Zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - run: zig fmt --check src/*.zig src/**/*.zig
